"""Global food database seed data — 145 common foods with USDA-sourced nutritional data."""

GLOBAL_FOOD_ITEMS = [
    {
        "name": "Apple",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 182,
        "serving_unit": "g",
        "calories": 95,
        "protein_g": 0.5,
        "carbs_g": 25.1,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 182, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 4.4,
            "potassium_mg": 195,
            "vitamin_c_mg": 8.4,
        },
    },
    {
        "name": "Banana",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 118,
        "serving_unit": "g",
        "calories": 105,
        "protein_g": 1.3,
        "carbs_g": 27.0,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 118, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.1,
            "potassium_mg": 422,
        },
    },
    {
        "name": "Orange",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 131,
        "serving_unit": "g",
        "calories": 62,
        "protein_g": 1.2,
        "carbs_g": 15.4,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 131, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 69.7,
        },
    },
    {
        "name": "Mango",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 165,
        "serving_unit": "g",
        "calories": 99,
        "protein_g": 1.4,
        "carbs_g": 24.7,
        "fat_g": 0.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 165, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 60.1,
        },
    },
    {
        "name": "Grapes",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 151,
        "serving_unit": "g",
        "calories": 104,
        "protein_g": 1.1,
        "carbs_g": 27.3,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 151, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "copper_mg": 0.2,
            "fibre_g": 1.4,
            "potassium_mg": 288.0,
            "vitamin_c_mg": 16.3,
            "vitamin_k_mcg": 22.0,
        },
    },
    {
        "name": "Strawberries",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 152,
        "serving_unit": "g",
        "calories": 49,
        "protein_g": 1.0,
        "carbs_g": 11.7,
        "fat_g": 0.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 152, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 89.4,
        },
    },
    {
        "name": "Blueberries",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 148,
        "serving_unit": "g",
        "calories": 84,
        "protein_g": 1.1,
        "carbs_g": 21.4,
        "fat_g": 0.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 148, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.6,
        },
    },
    {
        "name": "Watermelon",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 286,
        "serving_unit": "g",
        "calories": 86,
        "protein_g": 1.7,
        "carbs_g": 21.6,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '2 cups', 'grams': 286, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 1.1,
            "magnesium_mg": 29.0,
            "potassium_mg": 320.0,
            "vitamin_a_mcg": 43.0,
            "vitamin_c_mg": 23.2,
        },
    },
    {
        "name": "Pineapple",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 165,
        "serving_unit": "g",
        "calories": 82,
        "protein_g": 0.9,
        "carbs_g": 21.6,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 165, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 78.9,
        },
    },
    {
        "name": "Papaya",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 145,
        "serving_unit": "g",
        "calories": 62,
        "protein_g": 0.7,
        "carbs_g": 15.7,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 145, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 88.3,
        },
    },
    {
        "name": "Kiwi",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 69,
        "serving_unit": "g",
        "calories": 42,
        "protein_g": 0.8,
        "carbs_g": 10.1,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 69, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 64.0,
        },
    },
    {
        "name": "Peach",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 150,
        "serving_unit": "g",
        "calories": 59,
        "protein_g": 1.4,
        "carbs_g": 14.3,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 150, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 6.0,
            "fibre_g": 1.5,
            "folate_mcg": 4.0,
            "iron_mg": 0.3,
            "magnesium_mg": 9.0,
            "potassium_mg": 190.0,
            "sodium_mg": 0.0,
            "vitamin_a_mcg": 16.0,
            "vitamin_c_mg": 6.6,
            "vitamin_k_mcg": 2.6,
        },
    },
    {
        "name": "Pear",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 178,
        "serving_unit": "g",
        "calories": 101,
        "protein_g": 0.6,
        "carbs_g": 27.1,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 178, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 5.5,
        },
    },
    {
        "name": "Avocado",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 68,
        "serving_unit": "g",
        "calories": 114,
        "protein_g": 1.3,
        "carbs_g": 6.0,
        "fat_g": 10.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1/2', 'grams': 68, 'is_default': True}, {'label': '1 whole', 'grams': 136}, {'label': '100g', 'grams': 100}],
            "fibre_g": 4.6,
            "potassium_mg": 345,
        },
    },
    {
        "name": "Pomegranate",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 174,
        "serving_unit": "g",
        "calories": 144,
        "protein_g": 2.9,
        "carbs_g": 32.5,
        "fat_g": 2.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 174, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 7.0,
        },
    },
    {
        "name": "Guava",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 55,
        "serving_unit": "g",
        "calories": 37,
        "protein_g": 1.4,
        "carbs_g": 7.9,
        "fat_g": 0.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 fruit', 'grams': 55, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 125.6,
        },
    },
    {
        "name": "Cherries",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 138,
        "serving_unit": "g",
        "calories": 87,
        "protein_g": 1.5,
        "carbs_g": 22.1,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 138, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 13.0,
            "fibre_g": 2.1,
            "folate_mcg": 4.0,
            "iron_mg": 0.4,
            "magnesium_mg": 11.0,
            "potassium_mg": 222.0,
            "sodium_mg": 0.0,
            "vitamin_a_mcg": 3.0,
            "vitamin_c_mg": 7.0,
            "vitamin_k_mcg": 2.1,
        },
    },
    {
        "name": "Grapefruit",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 123,
        "serving_unit": "g",
        "calories": 52,
        "protein_g": 0.9,
        "carbs_g": 13.1,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1/2', 'grams': 123, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 38.4,
        },
    },
    {
        "name": "Raspberries",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 123,
        "serving_unit": "g",
        "calories": 64,
        "protein_g": 1.5,
        "carbs_g": 14.7,
        "fat_g": 0.8,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 123, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 8.0,
        },
    },
    {
        "name": "Cantaloupe",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 177,
        "serving_unit": "g",
        "calories": 60,
        "protein_g": 1.5,
        "carbs_g": 14.4,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 177, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_a_mcg": 299,
        },
    },
    {
        "name": "Dates",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 24,
        "serving_unit": "g",
        "calories": 66,
        "protein_g": 0.4,
        "carbs_g": 18.0,
        "fat_g": 0.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 date', 'grams': 24, 'is_default': True}, {'label': '3 dates', 'grams': 72}],
            "potassium_mg": 167,
        },
    },
    {
        "name": "Coconut",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 80,
        "serving_unit": "g",
        "calories": 283,
        "protein_g": 2.7,
        "carbs_g": 12.2,
        "fat_g": 26.8,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 80, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 7.2,
        },
    },
    {
        "name": "Blackberries",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 144,
        "serving_unit": "g",
        "calories": 62,
        "protein_g": 2.0,
        "carbs_g": 13.8,
        "fat_g": 0.7,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 144, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 7.6,
        },
    },
    {
        "name": "Plum",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 66,
        "serving_unit": "g",
        "calories": 30,
        "protein_g": 0.5,
        "carbs_g": 7.5,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 66, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 6.0,
            "fibre_g": 1.4,
            "folate_mcg": 5.0,
            "iron_mg": 0.2,
            "magnesium_mg": 7.0,
            "potassium_mg": 157.0,
            "sodium_mg": 0.0,
            "vitamin_a_mcg": 17.0,
            "vitamin_c_mg": 9.5,
            "vitamin_k_mcg": 6.4,
        },
    },
    {
        "name": "Dragon Fruit",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 100,
        "serving_unit": "g",
        "calories": 60,
        "protein_g": 1.2,
        "carbs_g": 13.0,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '100g', 'grams': 100, 'is_default': True}],
            "fibre_g": 3.0,
        },
    },
    {
        "name": "Tangerine",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 88,
        "serving_unit": "g",
        "calories": 47,
        "protein_g": 0.7,
        "carbs_g": 11.7,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 88, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 23.5,
        },
    },
    {
        "name": "Lemon",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 58,
        "serving_unit": "g",
        "calories": 17,
        "protein_g": 0.6,
        "carbs_g": 5.4,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 fruit', 'grams': 58, 'is_default': True}],
            "vitamin_c_mg": 30.7,
        },
    },
    {
        "name": "Cranberries",
        "category": "Fruit",
        "region": "Global",
        "serving_size": 100,
        "serving_unit": "g",
        "calories": 46,
        "protein_g": 0.5,
        "carbs_g": 12.2,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 100, 'is_default': True}],
            "fibre_g": 4.6,
        },
    },
    {
        "name": "Broccoli",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 91,
        "serving_unit": "g",
        "calories": 31,
        "protein_g": 2.6,
        "carbs_g": 6.0,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 91, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 2.4,
            "vitamin_c_mg": 81.2,
        },
    },
    {
        "name": "Spinach (raw)",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 30,
        "serving_unit": "g",
        "calories": 7,
        "protein_g": 0.9,
        "carbs_g": 1.1,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 30, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "iron_mg": 0.8,
            "vitamin_a_mcg": 141,
        },
    },
    {
        "name": "Kale",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 67,
        "serving_unit": "g",
        "calories": 33,
        "protein_g": 2.2,
        "carbs_g": 6.7,
        "fat_g": 0.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 67, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 80.4,
        },
    },
    {
        "name": "Carrot",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 61,
        "serving_unit": "g",
        "calories": 25,
        "protein_g": 0.6,
        "carbs_g": 5.8,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 61, 'is_default': True}, {'label': '1 cup', 'grams': 128}, {'label': '100g', 'grams': 100}],
            "vitamin_a_mcg": 509,
        },
    },
    {
        "name": "Tomato",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 123,
        "serving_unit": "g",
        "calories": 22,
        "protein_g": 1.1,
        "carbs_g": 4.8,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 123, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "potassium_mg": 292,
            "vitamin_c_mg": 16.9,
        },
    },
    {
        "name": "Cucumber",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 301,
        "serving_unit": "g",
        "calories": 45,
        "protein_g": 2.0,
        "carbs_g": 11.0,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 whole', 'grams': 301, 'is_default': True}, {'label': '1 cup', 'grams': 119}, {'label': '100g', 'grams': 100}],
            "fibre_g": 1.5,
            "magnesium_mg": 39.0,
            "potassium_mg": 442.0,
            "vitamin_c_mg": 8.4,
            "vitamin_k_mcg": 49.4,
        },
    },
    {
        "name": "Bell Pepper (Red)",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 119,
        "serving_unit": "g",
        "calories": 37,
        "protein_g": 1.2,
        "carbs_g": 7.2,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 119, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 152.0,
        },
    },
    {
        "name": "Onion",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 110,
        "serving_unit": "g",
        "calories": 44,
        "protein_g": 1.2,
        "carbs_g": 10.3,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 110, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 1.9,
            "folate_mcg": 21.0,
            "potassium_mg": 161.0,
            "vitamin_b6_mg": 0.1,
            "vitamin_c_mg": 8.1,
        },
    },
    {
        "name": "Potato (baked)",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 173,
        "serving_unit": "g",
        "calories": 161,
        "protein_g": 4.3,
        "carbs_g": 36.6,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 173, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.8,
            "potassium_mg": 926,
        },
    },
    {
        "name": "Sweet Potato",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 114,
        "serving_unit": "g",
        "calories": 103,
        "protein_g": 2.3,
        "carbs_g": 23.6,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 114, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_a_mcg": 1096,
        },
    },
    {
        "name": "Cauliflower",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 107,
        "serving_unit": "g",
        "calories": 27,
        "protein_g": 2.1,
        "carbs_g": 5.3,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 107, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 51.6,
        },
    },
    {
        "name": "Zucchini",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 113,
        "serving_unit": "g",
        "calories": 19,
        "protein_g": 1.4,
        "carbs_g": 3.5,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 113, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 16.0,
            "fibre_g": 1.0,
            "folate_mcg": 24.0,
            "iron_mg": 0.4,
            "magnesium_mg": 18.0,
            "potassium_mg": 261.0,
            "sodium_mg": 8.0,
            "vitamin_a_mcg": 10.0,
            "vitamin_c_mg": 17.9,
            "vitamin_k_mcg": 4.3,
        },
    },
    {
        "name": "Mushroom (White)",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 70,
        "serving_unit": "g",
        "calories": 15,
        "protein_g": 2.2,
        "carbs_g": 2.3,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 70, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "selenium_mcg": 6.5,
        },
    },
    {
        "name": "Lettuce (Romaine)",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 47,
        "serving_unit": "g",
        "calories": 8,
        "protein_g": 0.6,
        "carbs_g": 1.5,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 47, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_a_mcg": 205,
        },
    },
    {
        "name": "Cabbage",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 89,
        "serving_unit": "g",
        "calories": 22,
        "protein_g": 1.1,
        "carbs_g": 5.2,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 89, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 32.6,
        },
    },
    {
        "name": "Celery",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 101,
        "serving_unit": "g",
        "calories": 16,
        "protein_g": 0.7,
        "carbs_g": 3.0,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 101, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "potassium_mg": 263,
        },
    },
    {
        "name": "Asparagus",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 134,
        "serving_unit": "g",
        "calories": 27,
        "protein_g": 2.9,
        "carbs_g": 5.2,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 134, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "folate_mcg": 70,
        },
    },
    {
        "name": "Green Beans",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 125,
        "serving_unit": "g",
        "calories": 34,
        "protein_g": 2.0,
        "carbs_g": 7.8,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 125, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.4,
        },
    },
    {
        "name": "Peas",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 145,
        "serving_unit": "g",
        "calories": 117,
        "protein_g": 7.9,
        "carbs_g": 21.0,
        "fat_g": 0.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 145, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 8.8,
        },
    },
    {
        "name": "Corn",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 154,
        "serving_unit": "g",
        "calories": 132,
        "protein_g": 5.1,
        "carbs_g": 29.3,
        "fat_g": 1.8,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 154, 'is_default': True}, {'label': '1 ear', 'grams': 90}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.6,
        },
    },
    {
        "name": "Beetroot",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 136,
        "serving_unit": "g",
        "calories": 58,
        "protein_g": 2.2,
        "carbs_g": 13.0,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 136, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "folate_mcg": 148,
        },
    },
    {
        "name": "Pumpkin",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 116,
        "serving_unit": "g",
        "calories": 30,
        "protein_g": 1.2,
        "carbs_g": 7.5,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 116, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_a_mcg": 245,
        },
    },
    {
        "name": "Brussels Sprouts",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 88,
        "serving_unit": "g",
        "calories": 38,
        "protein_g": 3.0,
        "carbs_g": 7.9,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 88, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_c_mg": 74.8,
        },
    },
    {
        "name": "Edamame",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 155,
        "serving_unit": "g",
        "calories": 188,
        "protein_g": 18.5,
        "carbs_g": 13.8,
        "fat_g": 8.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 155, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 8.1,
        },
    },
    {
        "name": "Eggplant",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 82,
        "serving_unit": "g",
        "calories": 20,
        "protein_g": 0.8,
        "carbs_g": 4.8,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 82, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 2.5,
        },
    },
    {
        "name": "Garlic",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 3,
        "serving_unit": "g",
        "calories": 4,
        "protein_g": 0.2,
        "carbs_g": 1.0,
        "fat_g": 0.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 clove', 'grams': 3, 'is_default': True}, {'label': '3 cloves', 'grams': 9}],
            "calcium_mg": 181.0,
            "fibre_g": 2.1,
            "iron_mg": 1.7,
            "magnesium_mg": 25.0,
            "manganese_mg": 1.7,
            "phosphorus_mg": 153.0,
            "potassium_mg": 401.0,
            "selenium_mcg": 14.2,
            "sodium_mg": 17.0,
            "vitamin_b6_mg": 1.2,
            "vitamin_c_mg": 31.2,
            "zinc_mg": 1.2,
        },
    },
    {
        "name": "Okra",
        "category": "Vegetable",
        "region": "Global",
        "serving_size": 100,
        "serving_unit": "g",
        "calories": 33,
        "protein_g": 1.9,
        "carbs_g": 7.5,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 100, 'is_default': True}],
            "fibre_g": 3.2,
        },
    },
    {
        "name": "Chicken Breast",
        "category": "Protein",
        "region": "Global",
        "serving_size": 140,
        "serving_unit": "g",
        "calories": 231,
        "protein_g": 43.4,
        "carbs_g": 0.0,
        "fat_g": 5.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 breast', 'grams': 140, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 15.0,
            "cholesterol_mg": 85.0,
            "fibre_g": 0.0,
            "folate_mcg": 4.0,
            "iron_mg": 1.0,
            "magnesium_mg": 29.0,
            "phosphorus_mg": 228.0,
            "potassium_mg": 256.0,
            "selenium_mcg": 27.6,
            "sodium_mg": 74.0,
            "vitamin_a_mcg": 21.0,
            "vitamin_b12_mcg": 0.3,
            "vitamin_b6_mg": 0.6,
            "vitamin_c_mg": 1.6,
            "vitamin_d_mcg": 0.1,
            "zinc_mg": 1.0,
        },
    },
    {
        "name": "Chicken Thigh",
        "category": "Protein",
        "region": "Global",
        "serving_size": 116,
        "serving_unit": "g",
        "calories": 229,
        "protein_g": 28.3,
        "carbs_g": 0.0,
        "fat_g": 12.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 thigh', 'grams': 116, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 13.0,
            "cholesterol_mg": 93.0,
            "fibre_g": 0.0,
            "folate_mcg": 8.0,
            "iron_mg": 1.3,
            "magnesium_mg": 24.0,
            "phosphorus_mg": 179.0,
            "potassium_mg": 229.0,
            "selenium_mcg": 20.0,
            "sodium_mg": 95.0,
            "vitamin_a_mcg": 49.0,
            "vitamin_b12_mcg": 0.4,
            "vitamin_b6_mg": 0.3,
            "vitamin_c_mg": 0.0,
            "zinc_mg": 2.0,
        },
    },
    {
        "name": "Turkey Breast",
        "category": "Protein",
        "region": "Global",
        "serving_size": 140,
        "serving_unit": "g",
        "calories": 189,
        "protein_g": 40.6,
        "carbs_g": 0.0,
        "fat_g": 2.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 serving', 'grams': 140, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 10.0,
            "cholesterol_mg": 60.0,
            "fibre_g": 0.0,
            "folate_mcg": 5.0,
            "iron_mg": 1.4,
            "magnesium_mg": 27.0,
            "phosphorus_mg": 200.0,
            "potassium_mg": 249.0,
            "selenium_mcg": 30.0,
            "sodium_mg": 55.0,
            "vitamin_b12_mcg": 0.4,
            "vitamin_b6_mg": 0.5,
            "zinc_mg": 1.7,
        },
    },
    {
        "name": "Ground Beef (lean)",
        "category": "Protein",
        "region": "Global",
        "serving_size": 112,
        "serving_unit": "g",
        "calories": 196,
        "protein_g": 28.6,
        "carbs_g": 0.0,
        "fat_g": 8.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '4 oz', 'grams': 112, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "iron_mg": 2.7,
            "zinc_mg": 5.7,
        },
    },
    {
        "name": "Ground Beef (regular)",
        "category": "Protein",
        "region": "Global",
        "serving_size": 112,
        "serving_unit": "g",
        "calories": 287,
        "protein_g": 25.6,
        "carbs_g": 0.0,
        "fat_g": 19.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '4 oz', 'grams': 112, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "iron_mg": 2.5,
        },
    },
    {
        "name": "Beef Sirloin",
        "category": "Protein",
        "region": "Global",
        "serving_size": 85,
        "serving_unit": "g",
        "calories": 177,
        "protein_g": 26.1,
        "carbs_g": 0.0,
        "fat_g": 7.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '3 oz', 'grams': 85, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "iron_mg": 1.6,
            "zinc_mg": 4.5,
        },
    },
    {
        "name": "Pork Tenderloin",
        "category": "Protein",
        "region": "Global",
        "serving_size": 85,
        "serving_unit": "g",
        "calories": 120,
        "protein_g": 22.2,
        "carbs_g": 0.0,
        "fat_g": 3.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '3 oz', 'grams': 85, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "thiamin_mg": 0.8,
        },
    },
    {
        "name": "Bacon",
        "category": "Protein",
        "region": "Global",
        "serving_size": 8,
        "serving_unit": "g",
        "calories": 43,
        "protein_g": 3.0,
        "carbs_g": 0.1,
        "fat_g": 3.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 slice', 'grams': 8, 'is_default': True}, {'label': '3 slices', 'grams': 24}],
            "sodium_mg": 137,
        },
    },
    {
        "name": "Salmon",
        "category": "Protein",
        "region": "Global",
        "serving_size": 85,
        "serving_unit": "g",
        "calories": 175,
        "protein_g": 18.8,
        "carbs_g": 0.0,
        "fat_g": 10.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '3 oz', 'grams': 85, 'is_default': True}, {'label': '6 oz', 'grams': 170}, {'label': '100g', 'grams': 100}],
            "omega_3_g": 1.8,
            "vitamin_d_mcg": 11.1,
        },
    },
    {
        "name": "Tuna (canned)",
        "category": "Protein",
        "region": "Global",
        "serving_size": 85,
        "serving_unit": "g",
        "calories": 73,
        "protein_g": 16.5,
        "carbs_g": 0.0,
        "fat_g": 0.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '3 oz', 'grams': 85, 'is_default': True}, {'label': '1 can', 'grams': 142}, {'label': '100g', 'grams': 100}],
            "selenium_mcg": 56.0,
        },
    },
    {
        "name": "Shrimp",
        "category": "Protein",
        "region": "Global",
        "serving_size": 85,
        "serving_unit": "g",
        "calories": 84,
        "protein_g": 20.4,
        "carbs_g": 0.0,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '3 oz', 'grams': 85, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 70.0,
            "cholesterol_mg": 152.0,
            "fibre_g": 0.0,
            "iron_mg": 0.5,
            "magnesium_mg": 39.0,
            "omega_3_g": 0.3,
            "phosphorus_mg": 244.0,
            "potassium_mg": 259.0,
            "selenium_mcg": 38.0,
            "sodium_mg": 111.0,
            "vitamin_a_mcg": 54.0,
            "vitamin_b12_mcg": 1.1,
            "vitamin_d_mcg": 0.0,
            "zinc_mg": 1.6,
        },
    },
    {
        "name": "Cod",
        "category": "Protein",
        "region": "Global",
        "serving_size": 85,
        "serving_unit": "g",
        "calories": 70,
        "protein_g": 15.1,
        "carbs_g": 0.0,
        "fat_g": 0.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '3 oz', 'grams': 85, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 16.0,
            "cholesterol_mg": 43.0,
            "fibre_g": 0.0,
            "iron_mg": 0.4,
            "magnesium_mg": 32.0,
            "omega_3_g": 0.2,
            "phosphorus_mg": 203.0,
            "potassium_mg": 413.0,
            "selenium_mcg": 33.0,
            "sodium_mg": 78.0,
            "vitamin_a_mcg": 12.0,
            "vitamin_b12_mcg": 1.0,
            "vitamin_b6_mg": 0.2,
            "vitamin_d_mcg": 1.2,
            "zinc_mg": 0.5,
        },
    },
    {
        "name": "Tilapia",
        "category": "Protein",
        "region": "Global",
        "serving_size": 87,
        "serving_unit": "g",
        "calories": 109,
        "protein_g": 22.8,
        "carbs_g": 0.0,
        "fat_g": 2.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 fillet', 'grams': 87, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 14.0,
            "cholesterol_mg": 50.0,
            "fibre_g": 0.0,
            "iron_mg": 0.7,
            "magnesium_mg": 34.0,
            "phosphorus_mg": 204.0,
            "potassium_mg": 380.0,
            "selenium_mcg": 42.0,
            "sodium_mg": 52.0,
            "vitamin_b12_mcg": 1.6,
            "vitamin_d_mcg": 3.1,
            "zinc_mg": 0.4,
        },
    },
    {
        "name": "Sardines",
        "category": "Protein",
        "region": "Global",
        "serving_size": 92,
        "serving_unit": "g",
        "calories": 208,
        "protein_g": 24.6,
        "carbs_g": 0.0,
        "fat_g": 11.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 can', 'grams': 92, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 351,
            "omega_3_g": 1.4,
        },
    },
    {
        "name": "Eggs",
        "category": "Protein",
        "region": "Global",
        "serving_size": 50,
        "serving_unit": "g",
        "calories": 72,
        "protein_g": 6.3,
        "carbs_g": 0.4,
        "fat_g": 4.8,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 large', 'grams': 50, 'is_default': True}, {'label': '2 eggs', 'grams': 100}, {'label': '100g', 'grams': 100}],
            "vitamin_d_mcg": 1.0,
        },
    },
    {
        "name": "Egg Whites",
        "category": "Protein",
        "region": "Global",
        "serving_size": 33,
        "serving_unit": "g",
        "calories": 17,
        "protein_g": 3.6,
        "carbs_g": 0.2,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 white', 'grams': 33, 'is_default': True}, {'label': '3 whites', 'grams': 99}],
            "calcium_mg": 7.0,
            "cholesterol_mg": 0.0,
            "fibre_g": 0.0,
            "folate_mcg": 4.0,
            "iron_mg": 0.1,
            "magnesium_mg": 11.0,
            "phosphorus_mg": 15.0,
            "potassium_mg": 163.0,
            "selenium_mcg": 20.0,
            "sodium_mg": 166.0,
            "vitamin_b12_mcg": 0.1,
            "zinc_mg": 0.0,
        },
    },
    {
        "name": "Tofu (firm)",
        "category": "Protein",
        "region": "Global",
        "serving_size": 126,
        "serving_unit": "g",
        "calories": 88,
        "protein_g": 10.1,
        "carbs_g": 2.2,
        "fat_g": 5.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1/2 cup', 'grams': 126, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 253,
            "iron_mg": 1.8,
        },
    },
    {
        "name": "Tempeh",
        "category": "Protein",
        "region": "Global",
        "serving_size": 84,
        "serving_unit": "g",
        "calories": 162,
        "protein_g": 15.4,
        "carbs_g": 9.4,
        "fat_g": 9.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '3 oz', 'grams': 84, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 111.0,
            "copper_mg": 0.6,
            "fibre_g": 9.0,
            "folate_mcg": 24.0,
            "iron_mg": 2.7,
            "magnesium_mg": 81.0,
            "manganese_mg": 1.3,
            "phosphorus_mg": 266.0,
            "potassium_mg": 412.0,
            "sodium_mg": 9.0,
            "vitamin_b6_mg": 0.2,
            "zinc_mg": 1.1,
        },
    },
    {
        "name": "Lentils (cooked)",
        "category": "Protein",
        "region": "Global",
        "serving_size": 198,
        "serving_unit": "g",
        "calories": 230,
        "protein_g": 17.9,
        "carbs_g": 39.9,
        "fat_g": 0.8,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 198, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 15.6,
            "iron_mg": 6.6,
        },
    },
    {
        "name": "Chickpeas (cooked)",
        "category": "Protein",
        "region": "Global",
        "serving_size": 164,
        "serving_unit": "g",
        "calories": 269,
        "protein_g": 14.5,
        "carbs_g": 45.0,
        "fat_g": 4.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 164, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 12.5,
            "iron_mg": 4.7,
        },
    },
    {
        "name": "Black Beans (cooked)",
        "category": "Protein",
        "region": "Global",
        "serving_size": 172,
        "serving_unit": "g",
        "calories": 227,
        "protein_g": 15.2,
        "carbs_g": 40.8,
        "fat_g": 0.9,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 172, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 15.0,
        },
    },
    {
        "name": "Greek Yogurt",
        "category": "Protein",
        "region": "Global",
        "serving_size": 170,
        "serving_unit": "g",
        "calories": 100,
        "protein_g": 17.3,
        "carbs_g": 6.1,
        "fat_g": 0.7,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 170, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 187,
        },
    },
    {
        "name": "Cottage Cheese",
        "category": "Protein",
        "region": "Global",
        "serving_size": 113,
        "serving_unit": "g",
        "calories": 81,
        "protein_g": 14.0,
        "carbs_g": 3.2,
        "fat_g": 1.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1/2 cup', 'grams': 113, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 69,
        },
    },
    {
        "name": "Whey Protein",
        "category": "Protein",
        "region": "Global",
        "serving_size": 30,
        "serving_unit": "g",
        "calories": 113,
        "protein_g": 25.0,
        "carbs_g": 2.0,
        "fat_g": 0.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 scoop', 'grams': 30, 'is_default': True}, {'label': '2 scoops', 'grams': 60}],
            "calcium_mg": 150.0,
            "cholesterol_mg": 10.0,
            "fibre_g": 0.0,
            "iron_mg": 0.5,
            "magnesium_mg": 30.0,
            "phosphorus_mg": 120.0,
            "potassium_mg": 300.0,
            "sodium_mg": 200.0,
            "vitamin_b12_mcg": 0.5,
            "zinc_mg": 1.5,
        },
    },
    {
        "name": "Peanut Butter",
        "category": "Protein",
        "region": "Global",
        "serving_size": 32,
        "serving_unit": "g",
        "calories": 188,
        "protein_g": 8.0,
        "carbs_g": 6.0,
        "fat_g": 16.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '2 tbsp', 'grams': 32, 'is_default': True}, {'label': '1 tbsp', 'grams': 16}],
            "fibre_g": 1.9,
            "magnesium_mg": 49,
        },
    },
    {
        "name": "Almond Butter",
        "category": "Protein",
        "region": "Global",
        "serving_size": 32,
        "serving_unit": "g",
        "calories": 196,
        "protein_g": 6.8,
        "carbs_g": 6.0,
        "fat_g": 17.8,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '2 tbsp', 'grams': 32, 'is_default': True}, {'label': '1 tbsp', 'grams': 16}],
            "magnesium_mg": 89,
        },
    },
    {
        "name": "Chia Seeds",
        "category": "Protein",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 138,
        "protein_g": 4.7,
        "carbs_g": 12.0,
        "fat_g": 8.7,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '2 tbsp', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 9.8,
            "omega_3_g": 5.0,
        },
    },
    {
        "name": "Paneer",
        "category": "Protein",
        "region": "Indian",
        "serving_size": 100,
        "serving_unit": "g",
        "calories": 265,
        "protein_g": 18.3,
        "carbs_g": 1.2,
        "fat_g": 20.8,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '100g', 'grams': 100, 'is_default': True}, {'label': '50g', 'grams': 50}],
            "calcium_mg": 480,
        },
    },
    {
        "name": "White Rice (cooked)",
        "category": "Grain",
        "region": "Global",
        "serving_size": 158,
        "serving_unit": "g",
        "calories": 206,
        "protein_g": 4.3,
        "carbs_g": 44.5,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 158, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 10.0,
            "fibre_g": 0.4,
            "folate_mcg": 3.0,
            "iron_mg": 0.2,
            "magnesium_mg": 12.0,
            "phosphorus_mg": 43.0,
            "potassium_mg": 35.0,
            "sodium_mg": 1.0,
            "thiamin_mg": 0.0,
            "zinc_mg": 0.5,
        },
    },
    {
        "name": "Brown Rice (cooked)",
        "category": "Grain",
        "region": "Global",
        "serving_size": 195,
        "serving_unit": "g",
        "calories": 216,
        "protein_g": 5.0,
        "carbs_g": 44.8,
        "fat_g": 1.8,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 195, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.5,
        },
    },
    {
        "name": "Quinoa (cooked)",
        "category": "Grain",
        "region": "Global",
        "serving_size": 185,
        "serving_unit": "g",
        "calories": 222,
        "protein_g": 8.1,
        "carbs_g": 39.4,
        "fat_g": 3.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 185, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 5.2,
            "iron_mg": 2.8,
        },
    },
    {
        "name": "Oats (dry)",
        "category": "Grain",
        "region": "Global",
        "serving_size": 40,
        "serving_unit": "g",
        "calories": 150,
        "protein_g": 5.3,
        "carbs_g": 27.0,
        "fat_g": 2.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1/2 cup', 'grams': 40, 'is_default': True}, {'label': '1 cup', 'grams': 80}, {'label': '100g', 'grams': 100}],
            "fibre_g": 4.0,
        },
    },
    {
        "name": "Whole Wheat Bread",
        "category": "Grain",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 69,
        "protein_g": 3.6,
        "carbs_g": 11.6,
        "fat_g": 1.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 slice', 'grams': 28, 'is_default': True}, {'label': '2 slices', 'grams': 56}],
            "fibre_g": 1.9,
        },
    },
    {
        "name": "White Bread",
        "category": "Grain",
        "region": "Global",
        "serving_size": 25,
        "serving_unit": "g",
        "calories": 67,
        "protein_g": 1.9,
        "carbs_g": 12.7,
        "fat_g": 0.8,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 slice', 'grams': 25, 'is_default': True}, {'label': '2 slices', 'grams': 50}],
            "calcium_mg": 151.0,
            "fibre_g": 2.7,
            "folate_mcg": 114.0,
            "iron_mg": 3.6,
            "magnesium_mg": 22.0,
            "phosphorus_mg": 91.0,
            "potassium_mg": 115.0,
            "selenium_mcg": 25.0,
            "sodium_mg": 491.0,
            "thiamin_mg": 0.5,
            "zinc_mg": 0.7,
        },
    },
    {
        "name": "Pasta (cooked)",
        "category": "Grain",
        "region": "Global",
        "serving_size": 140,
        "serving_unit": "g",
        "calories": 220,
        "protein_g": 8.1,
        "carbs_g": 43.2,
        "fat_g": 1.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 140, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 7.0,
            "fibre_g": 1.8,
            "folate_mcg": 7.0,
            "iron_mg": 0.5,
            "magnesium_mg": 18.0,
            "phosphorus_mg": 58.0,
            "potassium_mg": 44.0,
            "selenium_mcg": 26.0,
            "sodium_mg": 1.0,
            "thiamin_mg": 0.1,
            "zinc_mg": 0.5,
        },
    },
    {
        "name": "Tortilla (flour)",
        "category": "Grain",
        "region": "Global",
        "serving_size": 45,
        "serving_unit": "g",
        "calories": 140,
        "protein_g": 3.6,
        "carbs_g": 23.6,
        "fat_g": 3.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 45, 'is_default': True}, {'label': '1 large', 'grams': 64}],
            "calcium_mg": 160.0,
            "fibre_g": 2.0,
            "folate_mcg": 90.0,
            "iron_mg": 2.4,
            "magnesium_mg": 18.0,
            "phosphorus_mg": 90.0,
            "potassium_mg": 120.0,
            "sodium_mg": 407.0,
            "thiamin_mg": 0.4,
            "zinc_mg": 0.5,
        },
    },
    {
        "name": "Bagel",
        "category": "Grain",
        "region": "Global",
        "serving_size": 105,
        "serving_unit": "g",
        "calories": 270,
        "protein_g": 10.0,
        "carbs_g": 53.0,
        "fat_g": 1.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 bagel', 'grams': 105, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "iron_mg": 3.8,
        },
    },
    {
        "name": "Granola",
        "category": "Grain",
        "region": "Global",
        "serving_size": 55,
        "serving_unit": "g",
        "calories": 260,
        "protein_g": 6.0,
        "carbs_g": 33.0,
        "fat_g": 12.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1/2 cup', 'grams': 55, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.5,
        },
    },
    {
        "name": "Basmati Rice",
        "category": "Grain",
        "region": "Indian",
        "serving_size": 163,
        "serving_unit": "g",
        "calories": 210,
        "protein_g": 4.4,
        "carbs_g": 45.6,
        "fat_g": 0.5,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 163, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 10.0,
            "fibre_g": 0.4,
            "folate_mcg": 3.0,
            "iron_mg": 0.2,
            "magnesium_mg": 12.0,
            "phosphorus_mg": 43.0,
            "potassium_mg": 35.0,
            "sodium_mg": 1.0,
            "thiamin_mg": 0.0,
            "zinc_mg": 0.5,
        },
    },
    {
        "name": "Whole Milk",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 244,
        "serving_unit": "ml",
        "calories": 149,
        "protein_g": 8.0,
        "carbs_g": 11.7,
        "fat_g": 7.9,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 244, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "calcium_mg": 276,
        },
    },
    {
        "name": "Skim Milk",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 245,
        "serving_unit": "ml",
        "calories": 83,
        "protein_g": 8.3,
        "carbs_g": 12.2,
        "fat_g": 0.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 245, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "calcium_mg": 299,
        },
    },
    {
        "name": "Cheddar Cheese",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 113,
        "protein_g": 7.0,
        "carbs_g": 0.4,
        "fat_g": 9.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 200,
        },
    },
    {
        "name": "Mozzarella",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 85,
        "protein_g": 6.3,
        "carbs_g": 0.7,
        "fat_g": 6.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 143,
        },
    },
    {
        "name": "Butter",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 14,
        "serving_unit": "g",
        "calories": 102,
        "protein_g": 0.1,
        "carbs_g": 0.0,
        "fat_g": 11.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 14, 'is_default': True}, {'label': '1 pat', 'grams': 5}],
            "calcium_mg": 24.0,
            "cholesterol_mg": 215.0,
            "fibre_g": 0.0,
            "iron_mg": 0.0,
            "magnesium_mg": 2.0,
            "phosphorus_mg": 24.0,
            "potassium_mg": 24.0,
            "sodium_mg": 11.0,
            "vitamin_a_mcg": 684.0,
            "vitamin_d_mcg": 1.5,
            "vitamin_e_mg": 2.3,
            "zinc_mg": 0.1,
        },
    },
    {
        "name": "Almond Milk",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 240,
        "serving_unit": "ml",
        "calories": 30,
        "protein_g": 1.0,
        "carbs_g": 1.0,
        "fat_g": 2.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 240, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "calcium_mg": 451,
        },
    },
    {
        "name": "Oat Milk",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 240,
        "serving_unit": "ml",
        "calories": 120,
        "protein_g": 3.0,
        "carbs_g": 16.0,
        "fat_g": 5.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 240, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "calcium_mg": 350,
        },
    },
    {
        "name": "Yogurt (plain)",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 245,
        "serving_unit": "g",
        "calories": 149,
        "protein_g": 8.5,
        "carbs_g": 11.4,
        "fat_g": 8.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 245, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 296,
        },
    },
    {
        "name": "Ghee",
        "category": "Dairy",
        "region": "Indian",
        "serving_size": 14,
        "serving_unit": "g",
        "calories": 123,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 14.0,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 14, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 4.0,
            "cholesterol_mg": 256.0,
            "fibre_g": 0.0,
            "iron_mg": 0.0,
            "potassium_mg": 5.0,
            "sodium_mg": 0.0,
            "vitamin_a_mcg": 840.0,
            "vitamin_d_mcg": 1.5,
            "vitamin_e_mg": 2.8,
        },
    },
    {
        "name": "Feta Cheese",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 75,
        "protein_g": 4.0,
        "carbs_g": 1.2,
        "fat_g": 6.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 140,
        },
    },
    {
        "name": "Heavy Cream",
        "category": "Dairy",
        "region": "Global",
        "serving_size": 15,
        "serving_unit": "ml",
        "calories": 51,
        "protein_g": 0.3,
        "carbs_g": 0.4,
        "fat_g": 5.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 15, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "calcium_mg": 65.0,
            "cholesterol_mg": 137.0,
            "fibre_g": 0.0,
            "iron_mg": 0.0,
            "magnesium_mg": 6.0,
            "phosphorus_mg": 61.0,
            "potassium_mg": 75.0,
            "sodium_mg": 38.0,
            "vitamin_a_mcg": 348.0,
            "vitamin_d_mcg": 0.4,
            "vitamin_e_mg": 0.9,
            "zinc_mg": 0.2,
        },
    },
    {
        "name": "Almonds",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 164,
        "protein_g": 6.0,
        "carbs_g": 6.1,
        "fat_g": 14.2,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.5,
            "magnesium_mg": 76,
        },
    },
    {
        "name": "Walnuts",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 185,
        "protein_g": 4.3,
        "carbs_g": 3.9,
        "fat_g": 18.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "omega_3_g": 2.6,
        },
    },
    {
        "name": "Cashews",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 157,
        "protein_g": 5.2,
        "carbs_g": 8.6,
        "fat_g": 12.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "magnesium_mg": 83,
        },
    },
    {
        "name": "Peanuts",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 161,
        "protein_g": 7.3,
        "carbs_g": 4.6,
        "fat_g": 14.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 92.0,
            "copper_mg": 1.1,
            "fibre_g": 8.5,
            "folate_mcg": 240.0,
            "iron_mg": 4.6,
            "magnesium_mg": 168.0,
            "manganese_mg": 1.9,
            "phosphorus_mg": 376.0,
            "potassium_mg": 705.0,
            "sodium_mg": 18.0,
            "vitamin_e_mg": 8.3,
            "zinc_mg": 3.3,
        },
    },
    {
        "name": "Pistachios",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 159,
        "protein_g": 5.7,
        "carbs_g": 7.7,
        "fat_g": 12.9,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 105.0,
            "copper_mg": 1.3,
            "fibre_g": 10.6,
            "folate_mcg": 51.0,
            "iron_mg": 3.9,
            "magnesium_mg": 121.0,
            "manganese_mg": 1.2,
            "phosphorus_mg": 490.0,
            "potassium_mg": 1025.0,
            "sodium_mg": 1.0,
            "thiamin_mg": 0.9,
            "vitamin_a_mcg": 26.0,
            "vitamin_b6_mg": 1.7,
            "vitamin_e_mg": 2.9,
            "zinc_mg": 2.2,
        },
    },
    {
        "name": "Sunflower Seeds",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 165,
        "protein_g": 5.5,
        "carbs_g": 6.5,
        "fat_g": 14.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "vitamin_e_mg": 7.4,
        },
    },
    {
        "name": "Pumpkin Seeds",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 151,
        "protein_g": 7.0,
        "carbs_g": 5.0,
        "fat_g": 13.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "magnesium_mg": 150,
        },
    },
    {
        "name": "Flax Seeds",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 10,
        "serving_unit": "g",
        "calories": 55,
        "protein_g": 1.9,
        "carbs_g": 3.0,
        "fat_g": 4.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 10, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 2.8,
            "omega_3_g": 2.4,
        },
    },
    {
        "name": "Tahini",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 15,
        "serving_unit": "g",
        "calories": 89,
        "protein_g": 2.6,
        "carbs_g": 3.2,
        "fat_g": 8.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 15, 'is_default': True}, {'label': '2 tbsp', 'grams': 30}],
            "calcium_mg": 64,
        },
    },
    {
        "name": "Mixed Nuts",
        "category": "Nuts",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 172,
        "protein_g": 5.0,
        "carbs_g": 7.0,
        "fat_g": 15.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 80.0,
            "copper_mg": 1.0,
            "fibre_g": 7.0,
            "folate_mcg": 50.0,
            "iron_mg": 3.0,
            "magnesium_mg": 150.0,
            "phosphorus_mg": 350.0,
            "potassium_mg": 600.0,
            "sodium_mg": 15.0,
            "vitamin_e_mg": 7.0,
            "zinc_mg": 2.5,
        },
    },
    {
        "name": "Olive Oil",
        "category": "Oil",
        "region": "Global",
        "serving_size": 14,
        "serving_unit": "ml",
        "calories": 119,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 13.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 14, 'is_default': True}, {'label': '1 tsp', 'grams': 5}],
            "calcium_mg": 1.0,
            "cholesterol_mg": 0.0,
            "fibre_g": 0.0,
            "iron_mg": 0.6,
            "potassium_mg": 1.0,
            "sodium_mg": 2.0,
            "vitamin_e_mg": 14.4,
            "vitamin_k_mcg": 60.2,
        },
    },
    {
        "name": "Coconut Oil",
        "category": "Oil",
        "region": "Global",
        "serving_size": 14,
        "serving_unit": "ml",
        "calories": 121,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 13.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 14, 'is_default': True}, {'label': '1 tsp', 'grams': 5}],
            "calcium_mg": 0.0,
            "cholesterol_mg": 0.0,
            "fibre_g": 0.0,
            "iron_mg": 0.0,
            "sodium_mg": 0.0,
            "vitamin_e_mg": 0.1,
            "vitamin_k_mcg": 0.5,
        },
    },
    {
        "name": "Avocado Oil",
        "category": "Oil",
        "region": "Global",
        "serving_size": 14,
        "serving_unit": "ml",
        "calories": 124,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 14.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 14, 'is_default': True}],
            "calcium_mg": 0.0,
            "cholesterol_mg": 0.0,
            "fibre_g": 0.0,
            "iron_mg": 0.0,
            "sodium_mg": 0.0,
            "vitamin_e_mg": 12.6,
        },
    },
    {
        "name": "Sesame Oil",
        "category": "Oil",
        "region": "Global",
        "serving_size": 14,
        "serving_unit": "ml",
        "calories": 120,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 13.6,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 tbsp', 'grams': 14, 'is_default': True}],
            "calcium_mg": 0.0,
            "cholesterol_mg": 0.0,
            "fibre_g": 0.0,
            "iron_mg": 0.0,
            "sodium_mg": 0.0,
            "vitamin_e_mg": 1.4,
            "vitamin_k_mcg": 13.6,
        },
    },
    {
        "name": "Coffee (black)",
        "category": "Beverage",
        "region": "Global",
        "serving_size": 237,
        "serving_unit": "ml",
        "calories": 2,
        "protein_g": 0.3,
        "carbs_g": 0.0,
        "fat_g": 0.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 237, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "potassium_mg": 116,
        },
    },
    {
        "name": "Green Tea",
        "category": "Beverage",
        "region": "Global",
        "serving_size": 237,
        "serving_unit": "ml",
        "calories": 2,
        "protein_g": 0.5,
        "carbs_g": 0.0,
        "fat_g": 0.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 237, 'is_default': True}],
            "calcium_mg": 0.0,
            "fibre_g": 0.0,
            "iron_mg": 0.0,
            "magnesium_mg": 1.0,
            "potassium_mg": 8.0,
            "sodium_mg": 1.0,
            "vitamin_c_mg": 0.0,
        },
    },
    {
        "name": "Orange Juice",
        "category": "Beverage",
        "region": "Global",
        "serving_size": 248,
        "serving_unit": "ml",
        "calories": 112,
        "protein_g": 1.7,
        "carbs_g": 25.8,
        "fat_g": 0.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 248, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "vitamin_c_mg": 124,
        },
    },
    {
        "name": "Apple Juice",
        "category": "Beverage",
        "region": "Global",
        "serving_size": 248,
        "serving_unit": "ml",
        "calories": 114,
        "protein_g": 0.3,
        "carbs_g": 28.0,
        "fat_g": 0.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 248, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "potassium_mg": 250,
        },
    },
    {
        "name": "Coconut Water",
        "category": "Beverage",
        "region": "Global",
        "serving_size": 240,
        "serving_unit": "ml",
        "calories": 46,
        "protein_g": 1.7,
        "carbs_g": 8.9,
        "fat_g": 0.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 240, 'is_default': True}, {'label': '100ml', 'grams': 100}],
            "potassium_mg": 600,
        },
    },
    {
        "name": "Dark Chocolate",
        "category": "Snack",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 170,
        "protein_g": 2.2,
        "carbs_g": 13.0,
        "fat_g": 12.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "iron_mg": 3.4,
            "magnesium_mg": 64,
        },
    },
    {
        "name": "Popcorn (air-popped)",
        "category": "Snack",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 110,
        "protein_g": 3.1,
        "carbs_g": 22.1,
        "fat_g": 1.3,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '3 cups', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 3.6,
        },
    },
    {
        "name": "Hummus",
        "category": "Snack",
        "region": "Global",
        "serving_size": 30,
        "serving_unit": "g",
        "calories": 52,
        "protein_g": 2.4,
        "carbs_g": 4.6,
        "fat_g": 3.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '2 tbsp', 'grams': 30, 'is_default': True}, {'label': '1/4 cup', 'grams': 62}],
            "fibre_g": 1.5,
        },
    },
    {
        "name": "Protein Bar",
        "category": "Snack",
        "region": "Global",
        "serving_size": 60,
        "serving_unit": "g",
        "calories": 210,
        "protein_g": 20.0,
        "carbs_g": 22.0,
        "fat_g": 7.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 bar', 'grams': 60, 'is_default': True}],
            "calcium_mg": 200.0,
            "fibre_g": 3.0,
            "iron_mg": 2.7,
            "potassium_mg": 150.0,
            "sodium_mg": 200.0,
        },
    },
    {
        "name": "Raisins",
        "category": "Snack",
        "region": "Global",
        "serving_size": 28,
        "serving_unit": "g",
        "calories": 85,
        "protein_g": 0.9,
        "carbs_g": 22.5,
        "fat_g": 0.1,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 oz', 'grams': 28, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "potassium_mg": 212,
        },
    },
    {
        "name": "Pancakes",
        "category": "Snack",
        "region": "Global",
        "serving_size": 77,
        "serving_unit": "g",
        "calories": 175,
        "protein_g": 4.8,
        "carbs_g": 22.2,
        "fat_g": 7.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 medium', 'grams': 77, 'is_default': True}, {'label': '2 pancakes', 'grams': 154}],
            "calcium_mg": 121.0,
            "cholesterol_mg": 37.0,
            "fibre_g": 1.5,
            "folate_mcg": 71.0,
            "iron_mg": 1.8,
            "magnesium_mg": 13.0,
            "phosphorus_mg": 192.0,
            "potassium_mg": 125.0,
            "sodium_mg": 439.0,
            "zinc_mg": 0.4,
        },
    },
    {
        "name": "Overnight Oats",
        "category": "Snack",
        "region": "Global",
        "serving_size": 245,
        "serving_unit": "g",
        "calories": 307,
        "protein_g": 11.0,
        "carbs_g": 51.0,
        "fat_g": 7.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 245, 'is_default': True}],
            "fibre_g": 5.0,
        },
    },
    {
        "name": "Sushi Rice",
        "category": "International",
        "region": "Japanese",
        "serving_size": 186,
        "serving_unit": "g",
        "calories": 242,
        "protein_g": 4.4,
        "carbs_g": 53.4,
        "fat_g": 0.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 186, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 3.0,
            "fibre_g": 0.3,
            "iron_mg": 0.2,
            "magnesium_mg": 8.0,
            "phosphorus_mg": 33.0,
            "potassium_mg": 29.0,
            "sodium_mg": 1.0,
            "zinc_mg": 0.4,
        },
    },
    {
        "name": "Miso Soup",
        "category": "International",
        "region": "Japanese",
        "serving_size": 240,
        "serving_unit": "ml",
        "calories": 40,
        "protein_g": 3.0,
        "carbs_g": 5.0,
        "fat_g": 1.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 240, 'is_default': True}],
            "calcium_mg": 20.0,
            "fibre_g": 0.5,
            "iron_mg": 0.7,
            "magnesium_mg": 12.0,
            "potassium_mg": 102.0,
            "sodium_mg": 634.0,
            "zinc_mg": 0.3,
        },
    },
    {
        "name": "Kimchi",
        "category": "International",
        "region": "Korean",
        "serving_size": 150,
        "serving_unit": "g",
        "calories": 23,
        "protein_g": 1.6,
        "carbs_g": 4.0,
        "fat_g": 0.5,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 150, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 2.4,
        },
    },
    {
        "name": "Falafel",
        "category": "International",
        "region": "Middle Eastern",
        "serving_size": 17,
        "serving_unit": "g",
        "calories": 57,
        "protein_g": 2.3,
        "carbs_g": 5.4,
        "fat_g": 3.4,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 piece', 'grams': 17, 'is_default': True}, {'label': '4 pieces', 'grams': 68}],
            "calcium_mg": 54.0,
            "copper_mg": 0.4,
            "fibre_g": 4.0,
            "folate_mcg": 58.0,
            "iron_mg": 3.4,
            "magnesium_mg": 82.0,
            "phosphorus_mg": 192.0,
            "potassium_mg": 298.0,
            "sodium_mg": 294.0,
            "zinc_mg": 1.5,
        },
    },
    {
        "name": "Pad Thai",
        "category": "International",
        "region": "Thai",
        "serving_size": 275,
        "serving_unit": "g",
        "calories": 400,
        "protein_g": 15.0,
        "carbs_g": 55.0,
        "fat_g": 14.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 serving', 'grams': 275, 'is_default': True}],
            "calcium_mg": 40.0,
            "cholesterol_mg": 50.0,
            "fibre_g": 1.5,
            "iron_mg": 1.5,
            "magnesium_mg": 25.0,
            "potassium_mg": 200.0,
            "sodium_mg": 600.0,
            "vitamin_a_mcg": 80.0,
        },
    },
    {
        "name": "Biryani",
        "category": "International",
        "region": "Indian",
        "serving_size": 250,
        "serving_unit": "g",
        "calories": 400,
        "protein_g": 22.0,
        "carbs_g": 50.0,
        "fat_g": 12.0,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 serving', 'grams': 250, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 30.0,
            "fibre_g": 1.5,
            "iron_mg": 1.5,
            "magnesium_mg": 25.0,
            "potassium_mg": 200.0,
            "sodium_mg": 400.0,
            "vitamin_a_mcg": 50.0,
            "zinc_mg": 1.0,
        },
    },
    {
        "name": "Dal",
        "category": "International",
        "region": "Indian",
        "serving_size": 200,
        "serving_unit": "g",
        "calories": 180,
        "protein_g": 10.0,
        "carbs_g": 28.0,
        "fat_g": 3.0,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 200, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 6.0,
            "iron_mg": 3.0,
        },
    },
    {
        "name": "Butter Chicken",
        "category": "International",
        "region": "Indian",
        "serving_size": 250,
        "serving_unit": "g",
        "calories": 438,
        "protein_g": 28.0,
        "carbs_g": 12.0,
        "fat_g": 30.0,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 serving', 'grams': 250, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 80.0,
            "cholesterol_mg": 60.0,
            "fibre_g": 1.0,
            "iron_mg": 1.2,
            "magnesium_mg": 20.0,
            "potassium_mg": 250.0,
            "sodium_mg": 500.0,
            "vitamin_a_mcg": 150.0,
        },
    },
    {
        "name": "Chole",
        "category": "International",
        "region": "Indian",
        "serving_size": 200,
        "serving_unit": "g",
        "calories": 240,
        "protein_g": 10.0,
        "carbs_g": 32.0,
        "fat_g": 8.0,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 200, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "fibre_g": 8.0,
        },
    },
    {
        "name": "Idli",
        "category": "International",
        "region": "Indian",
        "serving_size": 40,
        "serving_unit": "g",
        "calories": 39,
        "protein_g": 2.0,
        "carbs_g": 8.0,
        "fat_g": 0.2,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 piece', 'grams': 40, 'is_default': True}, {'label': '3 pieces', 'grams': 120}],
            "calcium_mg": 20.0,
            "fibre_g": 1.2,
            "folate_mcg": 15.0,
            "iron_mg": 0.8,
            "magnesium_mg": 15.0,
            "potassium_mg": 80.0,
            "sodium_mg": 200.0,
        },
    },
    {
        "name": "Dosa",
        "category": "International",
        "region": "Indian",
        "serving_size": 100,
        "serving_unit": "g",
        "calories": 168,
        "protein_g": 4.0,
        "carbs_g": 28.0,
        "fat_g": 4.0,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 dosa', 'grams': 100, 'is_default': True}, {'label': '2 dosas', 'grams': 200}],
            "calcium_mg": 25.0,
            "fibre_g": 1.5,
            "folate_mcg": 20.0,
            "iron_mg": 1.0,
            "magnesium_mg": 18.0,
            "potassium_mg": 100.0,
            "sodium_mg": 250.0,
        },
    },
    {
        "name": "Samosa",
        "category": "International",
        "region": "Indian",
        "serving_size": 100,
        "serving_unit": "g",
        "calories": 262,
        "protein_g": 5.0,
        "carbs_g": 28.0,
        "fat_g": 14.0,
        "source": "verified",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 piece', 'grams': 100, 'is_default': True}, {'label': '2 pieces', 'grams': 200}],
            "calcium_mg": 30.0,
            "cholesterol_mg": 10.0,
            "fibre_g": 2.0,
            "iron_mg": 1.5,
            "magnesium_mg": 20.0,
            "potassium_mg": 150.0,
            "sodium_mg": 350.0,
            "vitamin_a_mcg": 40.0,
        },
    },
    {
        "name": "Jollof Rice",
        "category": "International",
        "region": "West African",
        "serving_size": 175,
        "serving_unit": "g",
        "calories": 260,
        "protein_g": 5.0,
        "carbs_g": 42.0,
        "fat_g": 8.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 cup', 'grams': 175, 'is_default': True}, {'label': '100g', 'grams': 100}],
            "calcium_mg": 25.0,
            "fibre_g": 1.2,
            "iron_mg": 1.0,
            "magnesium_mg": 20.0,
            "potassium_mg": 150.0,
            "sodium_mg": 350.0,
            "vitamin_a_mcg": 100.0,
            "vitamin_c_mg": 15.0,
        },
    },
    {
        "name": "Injera",
        "category": "International",
        "region": "Ethiopian",
        "serving_size": 100,
        "serving_unit": "g",
        "calories": 145,
        "protein_g": 5.0,
        "carbs_g": 28.0,
        "fat_g": 1.0,
        "source": "usda",
        "micro_nutrients": {
            "_serving_options": [{'label': '1 piece', 'grams': 100, 'is_default': True}],
            "iron_mg": 3.0,
        },
    },
]
